latent_dim: 128

dataset:
  width: 64
  height: 64
  identity_folders:
    - "/Users/thomasr/Documents/deepfakes/test_data/64x64/tom_1min_no_glasses"
    - "/Users/thomasr/Documents/deepfakes/test_data/64x64/tom_1min_black_glasses"
    - "/Users/thomasr/Documents/deepfakes/test_data/64x64/tom_1min_blue_glasses"

encoder:
  in_channels: 3
  blocks: [2, 2, 4, 4]
  channels:
    - 32
    - 64
    - ${latent_dim}
    - ${latent_dim}

decoder:
  out_channels: 3
  blocks: [4, 4, 2, 2]
  channels:
    - ${latent_dim}
    - ${latent_dim}
    - 64
    - 32
  identity_dim: 128
  upsample_mode: "bilinear"

discriminator:
  in_channels: ${latent_dim}
  num_classes: 3
  lambda_inv: 1.0
  learning_rate: 0.001

training:
  batch_size: 32
  learning_rate: 0.001
  max_epochs: 100
  seed: 42
  steps_per_epoch: 500
  workers: 0
