dataset:
  width: 64
  height: 64
  identity_folders:
    - "/Users/thomasr/Documents/deepfakes/test_data/64x64"

encoder:
  in_channels: 3
  blocks: [2, 2, 4, 4]
  channels: [32, 64, 128, 128]

decoder:
  out_channels: 3
  blocks: [4, 4, 2, 2]
  channels: [128, 128, 64, 32]
  identity_dim: 128
  upsample_mode: "bilinear"

discriminator:
  enabled: false

training:
  batch_size: 32
  learning_rate: 0.0001
  max_epochs: 100
  seed: 42
  steps_per_epoch: 1000
  workers: 0
