experiments:
  - name: acrobot_random_baseline
    environment:
      id: Acrobot-v1
    policy:
      hidden_size: 128
    training:
      max_epochs: 50
      learning_rate: 1.0e-3
      batch_size: 256
    runner:
      max_iterations: 10
      episodes_per_iteration: 20
      render_interval_seconds: 60
      video_directory: videos
      data_directory: recorded_episodes
