model:
  hidden_dim: 64
  output_dim: 1
  num_hypotheses: 32
  learning_rate: 0.001

  classifier:
    hidden_dims: [64,64]
  predictor:
    hidden_dims: [64,64]
  generator:
    input_hidden_dims: [64,64]
    on_hot_hidden_dims: [64,64]
    output_hidden_dims: [64,64]


dataset:
  batch_size: 256

training:
  max_steps: 20000
