model:
  hidden_dim: 32
  output_dim: 1
  num_hypotheses: 8
  learning_rate: 0.001

  classifier:
    hidden_dims: [32]
  predictor:
    hidden_dims: [32]
  generator:
    hidden_dims: [32]


dataset:
  batch_size: 256

training:
  max_steps: 10000
